version: '3.8'

services:
  ai-newz:
    build:
      context: .
      dockerfile: Dockerfile.hf
    ports:
      - "7860:7860"
    environment:
      - PYTHONPATH=/app
      - PORT=7860
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
